### ISSUE TITLE
invalid image generated

### ISSUE THREAD

**Issue by leeyeh** [neocotic/qrious#50]
![default](https://cloud.githubusercontent.com/assets/175227/16714337/26a4053c-46f2-11e6-8b69-d9170aadf301.png)

http://jsbin.com/rusisijila/edit?html,js,output
<details>
```javascript
new QRious({
  value: 'https://url.leanapp.cn/UcPRalN',
  size: 180,
}).toDataURL()
```
 v2.0.1
</details>

**Comment by neocotic** [comment]
It does appear to be a different QR code than is generated by v1, which it shouldn't be. I'll try to look into this soon.

**Comment by neocotic** [comment]
I managed to find the source of this bug and fix it. I'm just about to get 2.0.2 released now just for this bug fix. Sorry for taking a while to get around to fixing this but I've been busy.

Thanks for your patience and I hope this allows you to use QRious reliably.

**Comment by neocotic** [comment]
A fix for this bug has just been released. Please upgrade to 2.0.2.
