### ISSUE TITLE
Transparent background? 

### ISSUE THREAD

**Issue by timmyomahony** [neocotic/qrious#63]
Is it possible to have a transparent background? I tried 

```
const qr = new QRious({
  element: ...,
  foreground: '#1a1a1a',
  background: 'transparent',  // also tried null and undefined
  value: 'https://github.com/neocotic/qrious',
  size: 500
});
```

but it doesn't work.

**Comment by neocotic** [comment]
Not currently supported but let's change that :)

I'm going to add 2 new options; `backgroundAlpha` and `foregroundAlpha`, both of which will default to `1.0`. The values can range between `0` and `1`. So, for your example;

``` javascript
const qr = new QRious({
  element: ...,
  foreground: '#1a1a1a',
  backgroundAlpha: 0,
  value: 'https://github.com/neocotic/qrious',
  size: 500
});
```

**Comment by neocotic** [comment]
@timmyomahony Please upgrade to v2.2.0 and let me know how you get on with these new options.

**Comment by timmyomahony** [comment]
Amazing. Thanks for the quick reply. Just updated and it works perfectly.
