### ISSUE TITLE
WebGL support

### ISSUE THREAD

**Issue by esteban-filardi** [neocotic/qrious#70]
Hi,

I'm trying to use this with PIXI.js for a game. PIXI.js uses webGl whenever available.The canvas is first created by PIXI.   It seems this library fails if the canvas is using webgl. 

Can anyone suggest me a solution using this library?

**Comment by neocotic** [comment]
@esteban-filardi I'm not familiar with PixiJS at all really but QRious is designed to generate the QR code and write it to the canvas provided (or create one where omitted). It is not designed to write to part of a canvas or to be embedded within a game as such as this would make the API more much complicated, more so than needed for intended usage.

Are you no able to overlay the QR canvas/image on top? I know this sounds hacky, but thought I'd check.

Apparently, [PixiJS supports loading images from data URLs](http://www.html5gamedevs.com/topic/14587-creating-sprite-from-data-uri-not-working-cross-origin-issues/), so you might want to try the following:

``` javascript
var qr = new QRious({ value: 'Hello, World!' })
var qrTexture = PIXI.Texture.fromImage(qr.toDataURL())
```

**Comment by esteban-filardi** [comment]
I was able to make it work with the snippet of code you sent. Thanks.
