### ISSUE TITLE
The qrios doesn't work correct with cyrillic symbols.

### ISSUE THREAD

**Issue by bububo** [neocotic/qrious#72]
Hello
I was trying to create QR code using any cyrillic words e.g 'Привет' but generated QR codes was incorrect. I couldn't scan it by my phone.

The online QR code generator http://www.qr-code-generator.com works fine with cyrillic words.

**Comment by neocotic** [comment]
@bububo Thanks for trying QRious. Unfortunately, the current version only supports ASCII characters (see #62). I'd love to support the full UTF-8 character set but this could take me a lot of time to determine how it's possible so I'm currently looking for help to do so.

**Comment by neocotic** [comment]
I'm closing this as a duplicate of #62 for now. That's not to say that your issue isn't valid, it just falls under an existing issue.

Please add any additional information on that issue.
